### ISSUE TITLE
Prompting user to force create a timestamped directory (feature update request)

### ISSUE THREAD

**Issue by abhinaykumar** [santumahapatra/notes#1]
Currently, it prompts the user twice to create a directory in the `year/month` format. Since, user has no other option but to say `yes` to it in order to create a note, creating a directory structure through the program itself sounds like a better idea.

for ex: 
Replacing the below code with the part where it prompts the user to create a directory should have the same impact. Also, this can be a default action in case you are planning to enable an option for user to set the directory and make it more configurable.
```
mkdir -p "${NOTES_DIRECTORY}/${YEAR}/${MONTH}"

echo "your notes are saved here: ${NOTES_DIRECTORY}/${YEAR}/${MONTH}"

```
what do you think?

**Comment by santumahapatra** [comment]
I think that is an excellent idea @abhinaykumar 

Thank for your kind thought. I had hacked together the initial version to get the folder structure done. 

I will make the updates and fix it in my next coding session.

**Comment by santumahapatra** [comment]
@abhinaykumar I have made the changes and incorporated them. Now we need not press y for each year and month.

I have still kept the prompt for the first time creation of the logs folder. I think that would be important to a use.
